version: '3'
services:
  alfresco:
    image: alfresco/alfresco-content-repository:${ALFRESCO_TAG}
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=search
        -Dsolr.port=8983
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        "
    ports:
      - "7203:7203" #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
      - "5005:5005" #Java debugging
      - "8081:8080" #Browser port for Alfresco
  share:
    image: alfresco/alfresco-share:${SHARE_TAG}
    environment:
      - REPO_HOST=alfresco
      - REPO_PORT=8080
    ports:
      - 8082:8080 #Browser port for Share
  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    ports:
      - 5432:5432
  search:
    image: quay.io/alfresco/insight-engine:${SEARCH_TAG}
    environment:
      #Replication properties
      - REPLICATION_TYPE=master
      #- REPLICATION_AFTER=commit,startup
      #- REPLICATION_CONFIG_FILES=schema.xml,stopwords.txt
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=search
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
      - 8083:8983 #Browser port
#  search_slave:
#    image: quay.io/alfresco/insight-engine:${SEARCH_TAG}
#    environment:
#      #Replication properties
#      - REPLICATION_TYPE=slave
#      - REPLICATION_MASTER_HOST=search
#      - REPLICATION_MASTER_PORT=8983
#      #- REPLICATION_MASTER_PROTOCOL=http
#      #- REPLICATION_CORE_NAME=alfresco
#      #- REPLICATION_POLL_INTERVAL=00:00:60
#      #Solr needs to know how to register itself with Alfresco
#      - SOLR_ALFRESCO_HOST=alfresco
#      - SOLR_ALFRESCO_PORT=8080
#      #Alfresco needs to know how to call solr
#      - SOLR_SOLR_HOST=search
#      - SOLR_SOLR_PORT=8983
#      #Create the default alfresco and archive cores
#      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
#    ports:
#      - 8084:8983 #Browser port